name:                lists-server
version:             0.1.0.0
github:              "githubuser/lists-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lists-server#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- http-types
- configurator
- resource-pool
- persistent
- persistent-template
- persistent-postgresql
- postgresql-simple
- resource-pool
- esqueleto
- monad-logger
- text
- aeson
- bytestring
- email-validate
- pwstore-purehaskell
- hspec
- QuickCheck
- deepseq
- wai
- wai-session
- cookie
- vault
- mtl


library:
  source-dirs: src

executables:
  lists-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lists-server

tests:
  lists-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lists-server
